language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
cache:
  directories:
    - $HOME/.composer/cache/files
install:
  - composer install
script:
  - vendor/bin/phpunit tests --bootstrap vendor/autoload.php --coverage-clover reports/coverage/clover.xml
after_script:
  # only if generated
  - if [ -f reports/coverage/clover.xml ]; then vendor/bin/test-reporter --coverage-report reports/coverage/clover.xml; fi
