language: php
php:
  - '5.5'
  - '5.6'
  - '7.3'
  - '7.4'
  - nightly
matrix:  
  allow_failures:
    - php: nightly  
cache:
  directories:
    - $HOME/.composer/cache/files
install:
  - composer install
script:
  - vendor/bin/phpunit tests
