language: php
jobs:
  include:
    - dist: trusty
      php:  '5.5'
    - dist: trusty
      php:  '5.6'
    - dist: xenial
      php:  '7.3'
    - dist: xenial
      php:  '7.4'
    - dist: xenial
      php:  nightly
matrix:  
  allow_failures:
    - php: nightly  
cache:
  directories:
    - $HOME/.composer/cache/files
install:
  - composer install
script:
  - vendor/bin/phpunit tests
